### ISSUE TITLE
Build throwing errors

### ISSUE THREAD

**Issue by mwsundberg** [thundernixon/Libre-Caslon#11]
I am trying to build the font from source and it always gets caught up and erroring out.

The build process I followed:
<details>
<summary>Commands executed in shell (in the repository folder):</summary>

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
chmod -R +x sources
rm -r fonts
bash sources/build.sh
```
</details>

<details>
<summary>build.sh output</summary>

```
Generating Static fonts
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "LibreCaslonText.glyphs" file into <GSFont>
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:fontmake.font_project:Generating instance UFO for "Libre Caslon Text Regular"
INFO:fontmake.font_project:Generating instance UFO for "Libre Caslon Text Medium"
INFO:fontmake.font_project:Generating instance UFO for "Libre Caslon Text SemiBold"
INFO:fontmake.font_project:Generating instance UFO for "Libre Caslon Text Bold"
INFO:fontmake.font_project:Building TTF for LibreCaslonText-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on LibreCaslonText-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on LibreCaslonText-Regular
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on LibreCaslonText-Regular
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 377, 2: 1392, 3: 470, 4: 72, 5: 12, 6: 11
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Saving ../fonts/LibreCaslonText-Regular.ttf
INFO:fontmake.font_project:Building TTF for LibreCaslonText-Medium
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on LibreCaslonText-Medium
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on LibreCaslonText-Medium
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on LibreCaslonText-Medium
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 400, 2: 1387, 3: 467, 4: 59, 5: 12, 6: 10
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Saving ../fonts/LibreCaslonText-Medium.ttf
INFO:fontmake.font_project:Building TTF for LibreCaslonText-SemiBold
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on LibreCaslonText-SemiBold
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on LibreCaslonText-SemiBold
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on LibreCaslonText-SemiBold
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 412, 2: 1370, 3: 456, 4: 73, 5: 11, 6: 10
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Saving ../fonts/LibreCaslonText-SemiBold.ttf
INFO:fontmake.font_project:Building TTF for LibreCaslonText-Bold
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on LibreCaslonText-Bold
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on LibreCaslonText-Bold
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on LibreCaslonText-Bold
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 387, 2: 1390, 3: 444, 4: 84, 5: 12, 6: 9
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Saving ../fonts/LibreCaslonText-Bold.ttf
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "LibreCaslonText-Italic.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Bold Italic'
INFO:fontmake.font_project:Interpolating master UFOs from designspace
Traceback (most recent call last):
  File "/home/wsl/font-libre-caslon/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/font_project.py", line 672, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/font_project.py", line 889, in run_from_designspace
    **kwargs,
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/font_project.py", line 932, in _run_from_designspace_static
    expand_features_to_instances=expand_features_to_instances,
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/font_project.py", line 707, in interpolate_instance_ufos
    designspace, round_geometry=round_instances
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/instantiator.py", line 215, in from_designspace
    masters_info = collect_info_masters(designspace, axis_bounds)
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontmake/instantiator.py", line 442, in collect_info_masters
    source.location, axis_bounds
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontTools/varLib/models.py", line 97, in normalizeLocation
    out[tag] = normalizeValue(v, triple)
  File "/home/wsl/font-libre-caslon/venv/lib/python3.6/site-packages/fontTools/varLib/models.py", line 46, in normalizeValue
    assert lower <= default <= upper, "invalid axis values: %3.3f, %3.3f %3.3f"%(lower, default, upper)
AssertionError: invalid axis values: 700.000, 700.000 550.000
```
</details>

Though this does produce fonts, I have to wonder if all is acting as it should.

The results of `ls fonts`:

```
LibreCaslonText-Bold.ttf
LibreCaslonText-Italic.ttf
LibreCaslonText-Medium.ttf
LibreCaslonText-Regular.ttf
LibreCaslonText-Roman-VF.ttf
LibreCaslonText-SemiBold.ttf
```

Additionally, it might be helpful to have some system information for context. I'm running this in WSL Ubuntu 18.04.

<details>
<summary>System information</summary>

Main OS: Windows 10 Pro 1909

WSL OS: Ubuntu 18.04.4 LTS

`python -V`: Python 3.6.9

`pip freeze`:

```
absl-py==0.9.0
appdirs==1.4.3
attrs==19.3.0
booleanOperations==0.9.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
compreffor==0.5.0
cu2qu==1.6.7
Deprecated==1.2.7
Flask==1.1.1
fontmake==2.0.9
fontMath==0.5.2
fonttools==4.3.0
fs==2.4.11
gftools==0.3.2
glyphsLib==5.1.6
idna==2.8
importlib-resources==1.0.2
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
opentype-sanitizer==8.0.0.post2
Pillow==7.0.0
pkg-resources==0.0.0
protobuf==3.11.3
pyclipper==1.1.0.post3
PyGithub==1.46
PyJWT==1.7.1
pytz==2019.3
requests==2.22.0
six==1.14.0
tabulate==0.8.6
ufo2ft==2.11.3
ufoLib2==0.5.1
Unidecode==1.1.1
urllib3==1.25.8
Werkzeug==1.0.0
wrapt==1.12.0
```
</details>

Also the font checking complains about what I gather is shell globbing:

<details>
<summary>bash sources/check.sh output</summary>

```
+ mkdir -p font_checks
++ ls fonts/LibreCaslonText-Bold.ttf fonts/LibreCaslonText-Italic.ttf fonts/LibreCaslonText-Medium.ttf fonts/LibreCaslonText-Regular.ttf fonts/LibreCaslonText-Roman-VF.ttf fonts/LibreCaslonText-SemiBold.ttf
+ ttfs='fonts/LibreCaslonText-Bold.ttf
fonts/LibreCaslonText-Italic.ttf
fonts/LibreCaslonText-Medium.ttf
fonts/LibreCaslonText-Regular.ttf
fonts/LibreCaslonText-Roman-VF.ttf
fonts/LibreCaslonText-SemiBold.ttf'
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-Bold-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-Bold.ttf --ghmarkdown fonts/LibreCaslonText-Bold-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-Bold-fontbakery-report.md font_checks/LibreCaslonText-Bold-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-Bold-fontbakery-report.md': No such file or directory
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-Italic-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-Italic.ttf --ghmarkdown fonts/LibreCaslonText-Italic-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-Italic-fontbakery-report.md font_checks/LibreCaslonText-Italic-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-Italic-fontbakery-report.md': No such file or directory
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-Medium-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-Medium.ttf --ghmarkdown fonts/LibreCaslonText-Medium-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-Medium-fontbakery-report.md font_checks/LibreCaslonText-Medium-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-Medium-fontbakery-report.md': No such file or directory
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-Regular-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-Regular.ttf --ghmarkdown fonts/LibreCaslonText-Regular-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-Regular-fontbakery-report.md font_checks/LibreCaslonText-Regular-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-Regular-fontbakery-report.md': No such file or directory
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-Roman-VF-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-Roman-VF.ttf --ghmarkdown fonts/LibreCaslonText-Roman-VF-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-Roman-VF-fontbakery-report.md font_checks/LibreCaslonText-Roman-VF-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-Roman-VF-fontbakery-report.md': No such file or directory
+ for ttf in $ttfs
+ fontCheck=fonts/LibreCaslonText-SemiBold-fontbakery-report.md
+ fontbakery check-googlefonts fonts/LibreCaslonText-SemiBold.ttf --ghmarkdown fonts/LibreCaslonText-SemiBold-fontbakery-report.md
sources/check.sh: line 9: fontbakery: command not found
+ mv fonts/LibreCaslonText-SemiBold-fontbakery-report.md font_checks/LibreCaslonText-SemiBold-fontbakery-report.md
mv: cannot stat 'fonts/LibreCaslonText-SemiBold-fontbakery-report.md': No such file or directory
```
</details>

**Comment by thundernixon** [comment]
Thanks for the report, @mwsundberg!

I’ve been redoing the build setup for this, after some extension + upgrade work in the Italics.

That’s a great idea to add some system info for the build scripts, however. I’ll do that in the updates.

**Comment by thundernixon** [comment]
Okay, I've removed the check script, as it works better to just use fontbakery directly, rather than trying to check all of them at once.

The build _should_ be working better now. If you'd like to, please try it again! I think that now that the masters have been set up to pass the Google Fonts review process, it should be working well.

I'll close this issue, but feel free to reopen if you have the same problem again.
